print("Hey you, Yes you! How are you doing my man! Could you remind me your name again? ")
name=input()
print()
food=input("Could you tell me your favourite food? ")
print()
song=input("What's your fave song of all time? ")
print()
location=input("Where do you live lol, deffo won't use it agaisnt your ass ")
print("So to sum it all up, your name is:",name,",You love:",food,",One of your favorite songs are:",song,",And your IP address points to",location)